import { describe, expect, it } from 'vitest';

import { loadPublicApi } from '../test/public-api';

/* =============================================================================
   LA SURFACE PUBLIQUE, ÉCRITE EN TOUTES LETTRES.

   Cette liste est le journal des noms que le paquet publie. Un nom qui
   apparaît ou disparaît fait rougir ce test : l'ajout se décide, il ne
   s'échappe pas d'un `export *`. Un nom retiré est une rupture ; en 3.x, il
   ne se retire pas, il se déprécie.
   ========================================================================== */

const EXPORT_NAMES = [
  'Autocomplete',
  'AutocompleteProps',
  'BackgroundSurface',
  'BackgroundSurfaceProps',
  'Badge',
  'BadgeProps',
  'BadgeTone',
  'Breadcrumb',
  'BreadcrumbProps',
  'BulletList',
  'BulletListProps',
  'Button',
  'ButtonProps',
  'ButtonVariant',
  'COOKIE_CONSENT_KEY',
  'Card',
  'CardGrid',
  'CardGridProps',
  'CardProps',
  'CatalogEntry',
  'Checkbox',
  'CheckboxProps',
  'Clipboard',
  'ClipboardProps',
  'CommandPalette',
  'CommandPaletteItem',
  'CommandPaletteLabels',
  'CommandPaletteProps',
  'ConfirmDialog',
  'ConfirmDialogLabels',
  'ConfirmDialogProps',
  'CookieBanner',
  'CookieBannerLabels',
  'CookieBannerProps',
  'CookieConsent',
  'DEFAULT_SITE_NAV_ITEMS',
  'DataTable',
  'DataTableColumn',
  'DataTableLabels',
  'DataTableProps',
  'DataTableRow',
  'DataTableSize',
  'DataTableSort',
  'DataTableSortDirection',
  'DescriptionList',
  'DescriptionListProps',
  'Divider',
  'DividerProps',
  'Donut',
  'DonutProps',
  'Dropzone',
  'DropzoneLabels',
  'DropzoneProps',
  'EmptyState',
  'EmptyStateProps',
  'Feedback',
  'FeedbackProps',
  'FeedbackTone',
  'FieldProps',
  'FileCard',
  'FileCardProps',
  'Form',
  'FormProps',
  'GlassSurfaceProps',
  'Heading',
  'HeadingLevel',
  'HeadingProps',
  'ICON_GROUPS',
  'ICON_KEYWORDS',
  'ICON_NAMES',
  'Icon',
  'IconActionButton',
  'IconActionButtonProps',
  'IconGroup',
  'IconProps',
  'InlineInput',
  'InlineInputProps',
  'Input',
  'InputProps',
  'Layout',
  'LayoutProps',
  'LegalLinks',
  'LegalLinksProps',
  'Lightbox',
  'LightboxLabels',
  'LightboxProps',
  'Link',
  'LinkProps',
  'Menu',
  'MenuProps',
  'Modal',
  'ModalLabels',
  'ModalProps',
  'MultiSelect',
  'MultiSelectProps',
  'NavItem',
  'Navbar',
  'NavbarProps',
  'OPALE_CATALOG',
  'OPALE_ICONS',
  'Opale',
  'OpaleIconName',
  'OpalePlacement',
  'OpaleSize',
  'OpaleTone',
  'OpaleUI',
  'PageScaffold',
  'PageScaffoldLanguage',
  'PageScaffoldLink',
  'PageScaffoldProps',
  'PageScaffoldSearchSuggestion',
  'PageScaffoldSlots',
  'PageScaffoldTheme',
  'Pagination',
  'PaginationLabels',
  'PaginationProps',
  'Pressable',
  'PressableProps',
  'ProgressBar',
  'ProgressBarProps',
  'Rating',
  'RatingInput',
  'RatingInputProps',
  'RatingProps',
  'SearchBar',
  'SearchBarProps',
  'SegmentedControl',
  'SegmentedControlProps',
  'Select',
  'SelectOption',
  'SelectProps',
  'SelectionBar',
  'SelectionBarProps',
  'SidePanel',
  'SidePanelLabels',
  'SidePanelProps',
  'Sidebar',
  'SidebarContextValue',
  'SidebarFooterProps',
  'SidebarHeaderProps',
  'SidebarItemProps',
  'SidebarItemsProps',
  'SidebarLabels',
  'SidebarProps',
  'SidebarToggleProps',
  'SiteNav',
  'SiteNavItem',
  'SiteNavProps',
  'Skeleton',
  'SkeletonProps',
  'Slider',
  'SliderProps',
  'Spinner',
  'SpinnerProps',
  'Stack',
  'StackProps',
  'StatCard',
  'StatCardProps',
  'SvgMap',
  'SvgMapBounds',
  'SvgMapControls',
  'SvgMapControlsLabels',
  'SvgMapControlsProps',
  'SvgMapFitOptions',
  'SvgMapLabels',
  'SvgMapMoveOptions',
  'SvgMapProps',
  'SvgMapRegion',
  'SvgMapViewportOptions',
  'SvgMapWheel',
  'Tabs',
  'TabsActivationMode',
  'TabsContentProps',
  'TabsContextValue',
  'TabsListProps',
  'TabsOrientation',
  'TabsProps',
  'TabsTriggerProps',
  'Text',
  'TextProps',
  'TextVariant',
  'Toast',
  'ToastAnimation',
  'ToastDefinition',
  'ToastLabels',
  'ToastPlacement',
  'ToastProps',
  'ToastProvider',
  'ToastProviderProps',
  'ToastTone',
  'Toggle',
  'ToggleProps',
  'Topbar',
  'TopbarActionsProps',
  'TopbarBrandProps',
  'TopbarContextValue',
  'TopbarDividerProps',
  'TopbarGap',
  'TopbarProps',
  'TopbarSectionProps',
  'UseSvgMapViewportResult',
  'isOpaleIconName',
  'readCookieConsent',
  'useSvgMapViewport',
  'useToast',
];

describe('la surface publique de `src/opale/index.ts`', () => {
  it('devrait publier exactement les noms attendus', () => {
    expect(loadPublicApi().exportNames).toEqual(EXPORT_NAMES);
  }, 60_000);
});

describe('les alias dépréciés de 3.6', () => {
  it.each(['OpaleUI', 'OPALE_CATALOG', 'CatalogEntry', 'DEFAULT_SITE_NAV_ITEMS'])(
    'devrait marquer %s `@deprecated` sans le retirer',
    (name) => {
      expect(loadPublicApi().isDeprecated(name)).toBe(true);
    },
    60_000,
  );

  it('ne devrait déprécier que `Background` dans le namespace `Opale`', () => {
    expect(loadPublicApi().isDeprecated('Opale')).toBe(false);
    expect(loadPublicApi().deprecatedMembersOf('Opale')).toEqual(['Background']);
  }, 60_000);
});
